version: '3'
services:
 
 reverse:
    build: ./proxy/
    container_name: production_nginx
    ports:
      - 80:80
      - 443:443
    networks:
    - example1

 app1:
   build: ./web/
   container_name: web
   ports:
   - "80"
   networks:
   - example1


networks:
  example1:
